In [76]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from keras.layers import Dense, SimpleRNN, LSTM,GRU
from keras.models import Sequential
from keras.preprocessing.sequence import TimeseriesGenerator
from sklearn.preprocessing import MinMaxScaler

In [77]:
df = pd.read_csv(r"C:\Users\Joel\Dropbox\My PC (LAPTOP-RQL6K54S)\Downloads\Sunspots.csv", index_col = 'Date', parse_dates=True)

In [78]:
scaler = MinMaxScaler(feature_range = (0,1))

In [79]:
df = scaler.fit_transform(df).flatten()

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
df.shape

(6530,)

In [82]:
x_train,x_test = train_test_split(df, test_size=0.20)

In [83]:
x_train.shape

(5224,)

In [84]:
x_test.shape

(1306,)

In [85]:
n_features = 1
n_inputs = 10

In [86]:
generator = TimeseriesGenerator(x_train,x_train,length= n_inputs, batch_size = 1)
generator_test = TimeseriesGenerator(x_test,x_test,length=n_inputs, batch_size = 1)

In [87]:
model = Sequential()
model.add(SimpleRNN(units=100,input_shape=(n_inputs,n_features),activation = 'tanh'))
model.add(Dense(units=1,activation='tanh'))

In [88]:
model.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])

In [89]:
history = model.fit(generator, epochs = 3)

Epoch 1/3
5214/5214 [==============================] - 16s 3ms/step - loss: 0.0832 - accuracy: 0.0104
Epoch 2/3
5214/5214 [==============================] - 14s 3ms/step - loss: 0.0793 - accuracy: 0.0104
Epoch 3/3
5214/5214 [==============================] - 14s 3ms/step - loss: 0.0788 - accuracy: 0.0104


In [95]:
score = model.evaluate(generator_test)

1296/1296 [==============================] - 3s 2ms/step - loss: 0.0791 - accuracy: 0.0000e+00


In [96]:
print(score)

[0.07909498363733292, 0.0]


In [92]:
model = Sequential()
model.add(LSTM(units=100,input_shape=(n_inputs,n_features),activation = 'tanh'))
model.add(Dense(units=5,activation='tanh'))

In [94]:
model.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])
history = model.fit(generator, epochs = 3)
score = model.predict(generator_test)
print(score)

Epoch 1/3
5214/5214 [==============================] - 26s 4ms/step - loss: 0.0782 - accuracy: 5.7537e-04
Epoch 2/3
5214/5214 [==============================] - 25s 5ms/step - loss: 0.0782 - accuracy: 0.0013
Epoch 3/3
1296/1296 [==============================] - 3s 2ms/step
[[0.35075733 0.35095495 0.3508641  0.35117832 0.3507777 ]
 [0.3489417  0.34898135 0.3490862  0.3492129  0.34910458]
 [0.34739402 0.3473587  0.34766838 0.3475421  0.3478957 ]
 ...
 [0.34938514 0.34948593 0.34939978 0.3492199  0.34913576]
 [0.34561    0.345947   0.34584072 0.3458686  0.34606835]
 [0.34729987 0.34763643 0.3472959  0.34727603 0.34752786]]


In [66]:
model = Sequential()
model.add(GRU(units=100,input_shape=(n_inputs,n_features),activation = 'tanh'))
model.add(Dense(units=1,activation='tanh'))

In [67]:
model.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])
history = model.fit(generator, epochs = 3)
score = model.predict(generator_test)
print(score)

Epoch 1/3
5214/5214 [==============================] - 30s 5ms/step - loss: 0.0809 - accuracy: 0.0109
Epoch 2/3
5214/5214 [==============================] - 27s 5ms/step - loss: 0.0797 - accuracy: 0.0111
Epoch 3/3
1296/1296 [==============================] - 5s 3ms/step
[[0.33591193]
 [0.32007766]
 [0.33366218]
 ...
 [0.3301945 ]
 [0.3234475 ]
 [0.33234644]]


398.2
